---
title: "Simulation 2 Results"
author: "Todd Burrows"
date: "2026-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(latex2exp)

options(scipen=999)
```

# Parameters
```{r,echo=FALSE}
sim_num <- 2 #Changing Dataset = 2
n_obs <- 1000
missp <- 0.4 #20% Missingness
sims <- 100 #100 #This must be the number of simulations in each independent simulation i.e. if doing 10 increments of 25 for 250 simulations, this is 25
M <- 12
maxiter <- 10
ntree <- 50
num_burn_in <- 500
num_iterations_after_burn_in <- 200

roundn <- 4

grad_num <- 1:5 #1:5 #These must be the iteration number labels, i.e. 1 to 10 for 10 simulations
gradual_sims <- sims #100
total_sims <- gradual_sims*length(grad_num) #500

true_beta_length <- 4
```

# Data Combining
```{r,echo=FALSE}
filename <- paste(sim_num,",",n_obs,",",missp,",",sims,",",M,",",maxiter,",",ntree,",",num_burn_in,",",num_iterations_after_burn_in,sep = "")
filename <- paste(filename, ".rds", sep = "")

sims <- total_sims

full_complete_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
full_complete_vcovs <- matrix(NA, ncol = true_beta_length, nrow=sims)

pmm_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
pmm_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
pmm_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
pmm_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
pmm_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

cart_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
cart_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
cart_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
cart_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
cart_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

rf_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
rf_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
rf_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
rf_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
rf_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

bart_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

full_sim_time <- numeric(sims)
full_pmm_time <- numeric(sims)
full_cart_time <- numeric(sims)
full_rf_time <- numeric(sims)
full_bart_time <- numeric(sims)

full_ovt <- 0

for(result_num in grad_num){
  filename_it <- paste(result_num,",",filename, sep="")
  filepath <- paste("/Users/toddb/Library/Mobile Documents/com~apple~CloudDocs/University/3rd Year/Project/Simulations/Sim2/SimsGrad/",filename_it, sep="")
  
  results <- readRDS(filepath)
  
  lower <- (result_num - 1)*gradual_sims + 1
  upper <- (lower - 1) + gradual_sims
  
  true_beta <- results[["true_beta"]]
  var_names <- results[["var_names"]]

  complete_coeffs <- results[["complete_coeffs"]]
  complete_vcovs <- results[["complete_vcovs"]]
  
  pmm_coeffs <- results[["pmm_coeffs"]]
  pmm_coverage_tot <- results[["pmm_coverage_tot"]]
  pmm_withins <- results [["pmm_withins"]]
  pmm_betweens <- results[["pmm_betweens"]]
  pmm_totals <- results[["pmm_totals"]]
  
  cart_coeffs <- results[["cart_coeffs"]]
  cart_coverage_tot <- results[["cart_coverage_tot"]]
  cart_withins <- results [["cart_withins"]]
  cart_betweens <- results[["cart_betweens"]]
  cart_totals <- results[["cart_totals"]]
  
  rf_coeffs <- results[["rf_coeffs"]]
  rf_coverage_tot <- results[["rf_coverage_tot"]]
  rf_withins <- results [["rf_withins"]]
  rf_betweens <- results[["rf_betweens"]]
  rf_totals <- results[["rf_totals"]]
  
  bart_coeffs <- results[["bart_coeffs"]]
  bart_coverage_tot <- results[["bart_coverage_tot"]]
  bart_withins <- results [["bart_withins"]]
  bart_betweens <- results[["bart_betweens"]]
  bart_totals <- results[["bart_totals"]]
  
  sim_time <- results[["sim_time"]]
  pmm_time <- results[["pmm_time"]]
  cart_time <- results[["cart_time"]]
  rf_time <- results[["rf_time"]]
  bart_time <- results[["bart_time"]]
  
  ovt <- results[["overall_time"]]
  
  full_complete_coeffs[lower:upper,] <- complete_coeffs
  full_complete_vcovs[lower:upper,] <- complete_vcovs
  
  pmm_full_coeffs[lower:upper,] <- pmm_coeffs
  pmm_full_coverage_tot[lower:upper,] <- pmm_coverage_tot
  pmm_full_withins[lower:upper,] <- pmm_withins
  pmm_full_betweens[lower:upper,] <- pmm_betweens
  pmm_full_totals[lower:upper,] <- pmm_totals
  
  cart_full_coeffs[lower:upper,] <- cart_coeffs
  cart_full_coverage_tot[lower:upper,] <- cart_coverage_tot
  cart_full_withins[lower:upper,] <- cart_withins
  cart_full_betweens[lower:upper,] <- cart_betweens
  cart_full_totals[lower:upper,] <- cart_totals
  
  rf_full_coeffs[lower:upper,] <- rf_coeffs
  rf_full_coverage_tot[lower:upper,] <- rf_coverage_tot
  rf_full_withins[lower:upper,] <- rf_withins
  rf_full_betweens[lower:upper,] <- rf_betweens
  rf_full_totals[lower:upper,] <- rf_totals
  
  bart_full_coeffs[lower:upper,] <- bart_coeffs
  bart_full_coverage_tot[lower:upper,] <- bart_coverage_tot
  bart_full_withins[lower:upper,] <- bart_withins
  bart_full_betweens[lower:upper,] <- bart_betweens
  bart_full_totals[lower:upper,] <- bart_totals
  
  full_sim_time[lower:upper] <- sim_time
  full_pmm_time[lower:upper] <- pmm_time
  full_cart_time[lower:upper] <- cart_time
  full_rf_time[lower:upper] <- rf_time
  full_bart_time[lower:upper] <- bart_time
  
  full_ovt <- full_ovt + ovt
}

true_beta <- true_beta

complete_lm_coeff <- colMeans(full_complete_coeffs)
complete_lm_vcov <- colMeans(full_complete_vcovs)

names(complete_lm_coeff) <- var_names

pmm_coeffs <- pmm_full_coeffs
pmm_bias_tru <- colMeans(pmm_coeffs) - true_beta
pmm_pb_tru <- 100*abs(pmm_bias_tru/true_beta)
pmm_coverage_tot <- colMeans(pmm_full_coverage_tot)
pmm_within_final <- colMeans(pmm_full_withins)
pmm_between_final <- colMeans(pmm_full_betweens)
pmm_total_final <- colMeans(pmm_full_totals)

cart_coeffs <- cart_full_coeffs
cart_bias_tru <- colMeans(cart_coeffs) - true_beta
cart_pb_tru <- 100*abs(cart_bias_tru/true_beta)
cart_coverage_tot <- colMeans(cart_full_coverage_tot)
cart_within_final <- colMeans(cart_full_withins)
cart_between_final <- colMeans(cart_full_betweens)
cart_total_final <- colMeans(cart_full_totals)

rf_coeffs <- rf_full_coeffs
rf_bias_tru <- colMeans(rf_coeffs) - true_beta
rf_pb_tru <- 100*abs(rf_bias_tru/true_beta)
rf_coverage_tot <- colMeans(rf_full_coverage_tot)
rf_within_final <- colMeans(rf_full_withins)
rf_between_final <- colMeans(rf_full_betweens)
rf_total_final <- colMeans(rf_full_totals)

bart_coeffs <- bart_full_coeffs
bart_bias_tru <- colMeans(bart_coeffs) - true_beta
bart_pb_tru <- 100*abs(bart_bias_tru/true_beta)
bart_coverage_tot <- colMeans(bart_full_coverage_tot)
bart_within_final <- colMeans(bart_full_withins)
bart_between_final <- colMeans(bart_full_betweens)
bart_total_final <- colMeans(bart_full_totals)

sim_time <- full_sim_time
pmm_time <- full_pmm_time
cart_time <- full_cart_time
rf_time <- full_rf_time
bart_time <- full_bart_time

ovt <- full_ovt

if(sim_num == 1){
  complete_lm_vcov <- diag(complete_lm_vcov)
}

coef_names <- names(complete_lm_coeff)

#rm(results)
```

```{r,echo=FALSE}
#Comparison values:
within_target <- complete_lm_vcov

between_target_pmm <- var(pmm_coeffs)
between_target_cart <- var(cart_coeffs)
between_target_rf <- var(rf_coeffs)
between_target_bart <- var(bart_coeffs)

total_target_pmm <- within_target + between_target_pmm
total_target_cart <- within_target + between_target_cart
total_target_rf <- within_target + between_target_rf
total_target_bart <- within_target + between_target_bart
```

```{r, echo=FALSE}
params <- data.frame(SimNumber = sim_num,
                     Observations = n_obs,
                     Missingness = missp,
                     Sims = sims,
                     M = M,
                     maxiter = maxiter,
                     ntree = ntree,
                     BurnIn = num_burn_in,
                     PostBurnIn = num_iterations_after_burn_in)

knitr::kable(params)
```

```{r, echo=FALSE}
mcses <- function(sims, true_beta, coeffs, coverage){
  bias_mcse <- apply(coeffs,2, sd) / sqrt(sims)
  pb_mcse <- 100*apply(coeffs,2, sd) / (sqrt(sims) * abs(true_beta))
  coverage_mcse <- sqrt((coverage*(1-coverage))/sims)
  
  return(list(bias_mcse, pb_mcse, coverage_mcse))
}

pmm_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = pmm_coeffs, coverage = pmm_coverage_tot)

cart_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = cart_coeffs, coverage = cart_coverage_tot)

rf_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = rf_coeffs, coverage = rf_coverage_tot)

bart_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = bart_coeffs, coverage = bart_coverage_tot)
```

```{r,echo=FALSE}
results <- tibble::tibble(Variable = c('$x_1$','','','','$x_2$','','','','${x_3}^2$','','','',"$\\sin(x_4)$",'','',''),
                    Method = c('$\\textsf{MICE-pmm}$','$\\textsf{MICE-cart}$','$\\textsf{MICE-rf}$','$\\textsf{properBART}$',
                               '$\\textsf{MICE-pmm}$','$\\textsf{MICE-cart}$','$\\textsf{MICE-rf}$','$\\textsf{properBART}$',
                               '$\\textsf{MICE-pmm}$','$\\textsf{MICE-cart}$','$\\textsf{MICE-rf}$','$\\textsf{properBART}$',
                               '$\\textsf{MICE-pmm}$','$\\textsf{MICE-cart}$','$\\textsf{MICE-rf}$','$\\textsf{properBART}$'),
                    `$\\text{PB}[\\beta_i]$` = c(paste0(round(pmm_pb_tru[1], digits = roundn)," (",round(pmm_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(cart_pb_tru[1], digits = roundn)," (",round(cart_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(rf_pb_tru[1], digits = roundn)," (",round(rf_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[1], digits = roundn)," (",round(bart_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(pmm_pb_tru[2], digits = roundn)," (",round(pmm_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(cart_pb_tru[2], digits = roundn)," (",round(cart_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(rf_pb_tru[2], digits = roundn)," (",round(rf_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[2], digits = roundn)," (",round(bart_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(pmm_pb_tru[3], digits = roundn)," (",round(pmm_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(cart_pb_tru[3], digits = roundn)," (",round(cart_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(rf_pb_tru[3], digits = roundn)," (",round(rf_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[3], digits = roundn)," (",round(bart_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(pmm_pb_tru[4], digits = roundn)," (",round(pmm_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(cart_pb_tru[4], digits = roundn)," (",round(cart_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(rf_pb_tru[4], digits = roundn)," (",round(rf_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[4], digits = roundn)," (",round(bart_mcse[[2]][4], digits = roundn),")")),
                    `$\\mathrm{Var}_\\text{T}$` = c(round(pmm_total_final[1], digits = roundn),
                                                    round(cart_total_final[1], digits = roundn),
                                                    round(rf_total_final[1], digits = roundn),
                                                    round(bart_total_final[1], digits = roundn),
                                                    round(pmm_total_final[2], digits = roundn),
                                                    round(cart_total_final[2], digits = roundn),
                                                    round(rf_total_final[2], digits = roundn),
                                                    round(bart_total_final[2], digits = roundn),
                                                    round(pmm_total_final[3], digits = roundn),
                                                    round(cart_total_final[3], digits = roundn),
                                                    round(rf_total_final[3], digits = roundn),
                                                    round(bart_total_final[3], digits = roundn),
                                                    round(pmm_total_final[4], digits = roundn),
                                                    round(cart_total_final[4], digits = roundn),
                                                    round(rf_total_final[4], digits = roundn),
                                                    round(bart_total_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{T}^{\\left(\\text{target}\\right)}$` = c(as.character(round(total_target_pmm[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_cart[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_rf[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_bart[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_pmm[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_cart[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_rf[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_bart[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_pmm[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_cart[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_rf[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_bart[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_pmm[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_cart[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_rf[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_bart[4,4],digits = roundn))),
                    `$\\mathrm{Var}_\\text{W}$` = c(round(pmm_within_final[1], digits = roundn),
                                                    round(cart_within_final[1], digits = roundn),
                                                    round(rf_within_final[1], digits = roundn),
                                                    round(bart_within_final[1], digits = roundn),
                                                    round(pmm_within_final[2], digits = roundn),
                                                    round(cart_within_final[2], digits = roundn),
                                                    round(rf_within_final[2], digits = roundn),
                                                    round(bart_within_final[2], digits = roundn),
                                                    round(pmm_within_final[3], digits = roundn),
                                                    round(cart_within_final[3], digits = roundn),
                                                    round(rf_within_final[3], digits = roundn),
                                                    round(bart_within_final[3], digits = roundn),
                                                    round(pmm_within_final[4], digits = roundn),
                                                    round(cart_within_final[4], digits = roundn),
                                                    round(rf_within_final[4], digits = roundn),
                                                    round(bart_within_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{W}^{\\left(\\text{target}\\right)}$` = c(as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn))),
                    `$\\mathrm{Var}_\\text{B}$` = c(round(pmm_between_final[1], digits = roundn),
                                                    round(cart_between_final[1], digits = roundn),
                                                    round(rf_between_final[1], digits = roundn),
                                                    round(bart_between_final[1], digits = roundn),
                                                    round(pmm_between_final[2], digits = roundn),
                                                    round(cart_between_final[2], digits = roundn),
                                                    round(rf_between_final[2], digits = roundn),
                                                    round(bart_between_final[2], digits = roundn),
                                                    round(pmm_between_final[3], digits = roundn),
                                                    round(cart_between_final[3], digits = roundn),
                                                    round(rf_between_final[3], digits = roundn),
                                                    round(bart_between_final[3], digits = roundn),
                                                    round(pmm_between_final[4], digits = roundn),
                                                    round(cart_between_final[4], digits = roundn),
                                                    round(rf_between_final[4], digits = roundn),
                                                    round(bart_between_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{B}^{\\left(\\text{target}\\right)}$` = c(as.character(round(between_target_pmm[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_cart[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_rf[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_bart[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_pmm[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_cart[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_rf[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_bart[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_pmm[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_cart[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_rf[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_bart[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_pmm[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_cart[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_rf[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_bart[4,4],digits = roundn))),
                    `Coverage Rate` = c(paste0(as.character(round(pmm_coverage_tot[1], digits = roundn))," (",round(pmm_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(cart_coverage_tot[1], digits = roundn))," (",round(cart_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(rf_coverage_tot[1], digits = roundn))," (",round(rf_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[1], digits = roundn))," (",round(bart_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(pmm_coverage_tot[2], digits = roundn))," (",round(pmm_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(cart_coverage_tot[2], digits = roundn))," (",round(cart_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(rf_coverage_tot[2], digits = roundn))," (",round(rf_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[2], digits = roundn))," (",round(bart_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(pmm_coverage_tot[3], digits = roundn))," (",round(pmm_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(cart_coverage_tot[3], digits = roundn))," (",round(cart_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(rf_coverage_tot[3], digits = roundn))," (",round(rf_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[3], digits = roundn))," (",round(bart_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(pmm_coverage_tot[4], digits = roundn))," (",round(pmm_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(cart_coverage_tot[4], digits = roundn))," (",round(cart_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(rf_coverage_tot[4], digits = roundn))," (",round(rf_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[4], digits = roundn))," (",round(bart_mcse[[3]][4], digits = roundn),")")))

knitr::kable(results, escape = FALSE)
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(sim_time[sim_out:length(sim_time)]),
                       Time = sim_time[sim_out:length(sim_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "lightgreen") +
  labs(title = "Plot showing the time take for each simulation.",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(pmm_time[sim_out:length(pmm_time)]),
                       Time = pmm_time[sim_out:length(pmm_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#000080") +
  labs(title = "Plot showing the time take for each PMM process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(cart_time[sim_out:length(cart_time)]),
                       Time = cart_time[sim_out:length(cart_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#f7a502") +
  labs(title = "Plot showing the time take for each CART process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(rf_time[sim_out:length(rf_time)]),
                       Time = rf_time[sim_out:length(rf_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#e93e6f") +
  labs(title = "Plot showing the time take for each RF process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(bart_time[sim_out:length(bart_time)]),
                       Time = bart_time[sim_out:length(bart_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#089cc0") +
  labs(title = "Plot showing the time take for each BART process",
       y = "Time (seconds)")
```

\hspace{10cm}

```{r, echo=FALSE}
ovt_mins <- ovt/60
ovt_hours <- ovt_mins/60
if(ovt_hours>2){
  rep_ovt <- ovt_hours
  com_ovt <- 'hours.'
} else if(ovt_mins>2){
  rep_ovt <- ovt_mins
  com_ovt <- 'minutes.'
} else{
  rep_ovt <- ovt
  com_ovt <- 'seconds.'
}
```

### Overall Time: `r rep_ovt` `r com_ovt`

```{r, echo=FALSE}
vals <- true_beta

colnames(pmm_coeffs) <- coef_names
colnames(cart_coeffs) <- coef_names
colnames(rf_coeffs) <- coef_names
colnames(bart_coeffs) <- coef_names

coefs.tb <- bind_rows(
  as_tibble(pmm_coeffs) %>%
    mutate(Method = "${MICE-pmm}$", Sim = row_number()),
  as_tibble(cart_coeffs) %>%
    mutate(Method = "${MICE-cart}$", Sim = row_number()),
  as_tibble(rf_coeffs) %>%
    mutate(Method = "${MICE-rf}$", Sim = row_number()),
  as_tibble(bart_coeffs) %>%
    mutate(Method = "${properBART}$", Sim = row_number())
) %>%
  pivot_longer(
    cols = all_of(coef_names),
    names_to = "Estimates",
    values_to = "coefs"
  ) %>%
  mutate(
    Method = factor(
      Method,
      levels = c(
        "${MICE-pmm}$",
        "${MICE-cart}$",
        "${MICE-rf}$",
        "${properBART}$"
      )
    ),
    Estimates = factor(Estimates, levels = coef_names)
  )

true.line <- tibble(
  Estimates = factor(coef_names, levels = coef_names),
  mean.hat = vals
)

colours <- c(
  "${MICE-pmm}$" = "#000080",
  "${MICE-cart}$" = "#f7a502",
  "${MICE-rf}$" = "#e93e6f",
  "${properBART}$" = "#089cc0"
)

labels.names <- c(
  "${MICE-pmm}$" = TeX("${MICE-pmm}$"),
  "${MICE-cart}$" = TeX("${MICE-cart}$"),
  "${MICE-rf}$" = TeX("${MICE-rf}$"),
  "${properBART}$" = TeX("${properBART}$")
)

ggplot(
  coefs.tb,
  aes(x = coefs, y = Method, color = Method, fill = Method)
) +
  geom_boxplot(width = 0.2, outlier.color = NA, alpha = 0.5) +
  facet_wrap(
    vars(Estimates),
    scales = "free_x",
    nrow = 2,
    labeller = label_parsed
  ) +
  geom_vline(
    data = true.line,
    aes(xintercept = mean.hat),
    linetype = "dashed"
  ) +
  scale_color_manual(values = colours) +
  scale_fill_manual(values = colours) +
  scale_y_discrete(labels = labels.names) +
  guides(color = "none", fill = "none") +
  labs(x = "Coefficient", y = "Method") +
  theme(
    axis.title.x = element_text(size = 26, margin = margin(t = 10)),
    axis.title.y = element_text(size = 26, margin = margin(r = 10)),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 18),
    strip.text.x = element_text(size = 18),
    panel.spacing.x = unit(0.35, "in"),
    panel.spacing.y = unit(0.2, "in")
  )
```


```{r, echo=FALSE}
true_between <- list(
  `MICE-pmm` = diag(var(pmm_coeffs)),
  `MICE-cart` = diag(var(cart_coeffs)),
  `MICE-rf`   = diag(var(rf_coeffs)),
  `properBART` = diag(var(bart_coeffs))
)

plot_df <- bind_rows(
  tibble(
    Estimates = coef_names,
    Method = "MICE-pmm",
    Between = as.numeric(pmm_between_final),
    True.Between = true_between$`MICE-pmm`
  ),
  tibble(
    Estimates = coef_names,
    Method = "MICE-cart",
    Between = as.numeric(cart_between_final),
    True.Between = true_between$`MICE-cart`
  ),
  tibble(
    Estimates = coef_names,
    Method = "MICE-rf",
    Between = as.numeric(rf_between_final),
    True.Between = true_between$`MICE-rf`
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBART",
    Between = as.numeric(bart_between_final),
    True.Between = true_between$`properBART`
  )
) %>%
  mutate(
    reratio.between = Between / True.Between - 1
  ) %>%
  pivot_longer(
    cols = c(reratio.between),
    names_to = "Type",
    values_to = "Value"
  ) %>%
  mutate(
    Estimates = factor(Estimates, levels = coef_names),
    Method = factor(Method, levels = c("MICE-pmm","MICE-cart","MICE-rf","properBART")),
    Type = factor(
      Type,
      levels = c("reratio.between"),
      labels = c(
        "Var[B] / Var[B]^{target} - 1"
      )
    )
  )

colours <- c(
  "MICE-pmm" = "#000080",
  "MICE-cart" = "#f7a502",
  "MICE-rf" = "#e93e6f",
  "properBART" = "#089cc0"
)

ggplot(
  plot_df,
  aes(x = Method, y = Value, fill = Method)
) +
  geom_col(position = "dodge") +
  facet_grid(
    Type ~ Estimates,
    switch = "y",
    labeller = label_parsed
  ) +
  scale_fill_manual(values = colours) +
  labs(
    x = "Method",
    y = "Relative Ratio"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text.y = element_text(size = 14, face = "bold"),
    strip.text.x = element_text(size = 12, face = "bold"),
    panel.spacing = unit(0.2, "in"),
    legend.position = "none"
  )
```

```{r, echo=FALSE}
true_within <- complete_lm_vcov

plot_df <- bind_rows(
  tibble(
    Estimates = coef_names,
    Method = "MICE-pmm",
    Within = as.numeric(pmm_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "MICE-cart",
    Within = as.numeric(cart_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "MICE-rf",
    Within = as.numeric(rf_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBART",
    Within = as.numeric(bart_within_final),
    True.Within = true_within,
  )
) %>%
  mutate(
    reratio.within  = Within  / True.Within  - 1
  ) %>%
  pivot_longer(
    cols = c(reratio.within),
    names_to = "Type",
    values_to = "Value"
  ) %>%
  mutate(
    Estimates = factor(Estimates, levels = coef_names),
    Method = factor(Method, levels = c("MICE-pmm","MICE-cart","MICE-rf","properBART")),
    Type = factor(
      Type,
      levels = c("reratio.within"),
      labels = c(
        "Var[W] / Var[W]^{target} - 1"
      )
    )
  )

colours <- c(
  "MICE-pmm" = "#000080",
  "MICE-cart" = "#f7a502",
  "MICE-rf" = "#e93e6f",
  "properBART" = "#089cc0"
)

ggplot(
  plot_df,
  aes(x = Method, y = Value, fill = Method)
) +
  geom_col(position = "dodge") +
  facet_grid(
    Type ~ Estimates,
    switch = "y",
    labeller = label_parsed
  ) +
  scale_fill_manual(values = colours) +
  labs(
    x = "Method",
    y = "Relative Ratio"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text.y = element_text(size = 14, face = "bold"),
    strip.text.x = element_text(size = 12, face = "bold"),
    panel.spacing = unit(0.2, "in"),
    legend.position = "none"
  )
```

