---
title: "Simulation 3 Results"
author: "Todd Burrows"
date: "2026-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(latex2exp)

options(scipen=999)
```

# Parameters
```{r,echo=FALSE}
sim_num <- 2 #Changing Dataset = 2
n_obs <- 1000
missp <- 0.4 #20% Missingness
sims <- 50 #50 #This must be the number of simulations in each independent simulation i.e. if doing 10 increments of 25 for 250 simulations, this is 25
M <- 12
maxiter <- 10
ntree <- 50
num_burn_in <- 500
num_iterations_after_burn_in <- 200

roundn <- 4

grad_num <- 1:5 #1:5 #These must be the iteration number labels, i.e. 1 to 10 for 10 simulations
gradual_sims <- sims #50
total_sims <- gradual_sims*length(grad_num) #250

true_beta_length <- 4
```

# Data Combining
```{r,echo=FALSE}
filename <- paste(sim_num,",",n_obs,",",missp,",",sims,",",M,",",maxiter,",",ntree,",",num_burn_in,",",num_iterations_after_burn_in,sep = "")
filename <- paste(filename, ".rds", sep = "")

sims <- total_sims

full_complete_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
full_complete_vcovs <- matrix(NA, ncol = true_beta_length, nrow=sims)

mean_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
mean_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
mean_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
mean_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
mean_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

meav_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
meav_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
meav_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
meav_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
meav_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

rand_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
rand_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
rand_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
rand_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
rand_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

bart_full_coeffs <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_coverage_tot <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_withins <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_betweens <- matrix(NA, ncol = true_beta_length, nrow=sims)
bart_full_totals <- matrix(NA, ncol = true_beta_length, nrow=sims)

full_sim_time <- numeric(sims)
full_mean_time <- numeric(sims)
full_meav_time <- numeric(sims)
full_rand_time <- numeric(sims)
full_bart_time <- numeric(sims)

full_ovt <- 0

for(result_num in grad_num){
  filename_it <- paste(result_num,",",filename, sep="")
  filepath <- paste("/Users/toddb/Library/Mobile Documents/com~apple~CloudDocs/University/3rd Year/Project/Simulations/Sim3/SimsGrad/",filename_it, sep="")
  
  results <- readRDS(filepath)
  
  lower <- (result_num - 1)*gradual_sims + 1
  upper <- (lower - 1) + gradual_sims
  
  true_beta <- results[["true_beta"]]
  var_names <- results[["var_names"]]

  complete_coeffs <- results[["complete_coeffs"]]
  complete_vcovs <- results[["complete_vcovs"]]
  
  mean_coeffs <- results[["mean_coeffs"]]
  mean_coverage_tot <- results[["mean_coverage_tot"]]
  mean_withins <- results [["mean_withins"]]
  mean_betweens <- results[["mean_betweens"]]
  mean_totals <- results[["mean_totals"]]
  
  meav_coeffs <- results[["meav_coeffs"]]
  meav_coverage_tot <- results[["meav_coverage_tot"]]
  meav_withins <- results [["meav_withins"]]
  meav_betweens <- results[["meav_betweens"]]
  meav_totals <- results[["meav_totals"]]
  
  rand_coeffs <- results[["rand_coeffs"]]
  rand_coverage_tot <- results[["rand_coverage_tot"]]
  rand_withins <- results [["rand_withins"]]
  rand_betweens <- results[["rand_betweens"]]
  rand_totals <- results[["rand_totals"]]
  
  bart_coeffs <- results[["bart_coeffs"]]
  bart_coverage_tot <- results[["bart_coverage_tot"]]
  bart_withins <- results [["bart_withins"]]
  bart_betweens <- results[["bart_betweens"]]
  bart_totals <- results[["bart_totals"]]
  
  sim_time <- results[["sim_time"]]
  mean_time <- results[["mean_time"]]
  meav_time <- results[["meav_time"]]
  rand_time <- results[["rand_time"]]
  bart_time <- results[["bart_time"]]
  
  ovt <- results[["overall_time"]]
  
  full_complete_coeffs[lower:upper,] <- complete_coeffs
  full_complete_vcovs[lower:upper,] <- complete_vcovs
  
  mean_full_coeffs[lower:upper,] <- mean_coeffs
  mean_full_coverage_tot[lower:upper,] <- mean_coverage_tot
  mean_full_withins[lower:upper,] <- mean_withins
  mean_full_betweens[lower:upper,] <- mean_betweens
  mean_full_totals[lower:upper,] <- mean_totals
  
  meav_full_coeffs[lower:upper,] <- meav_coeffs
  meav_full_coverage_tot[lower:upper,] <- meav_coverage_tot
  meav_full_withins[lower:upper,] <- meav_withins
  meav_full_betweens[lower:upper,] <- meav_betweens
  meav_full_totals[lower:upper,] <- meav_totals
  
  rand_full_coeffs[lower:upper,] <- rand_coeffs
  rand_full_coverage_tot[lower:upper,] <- rand_coverage_tot
  rand_full_withins[lower:upper,] <- rand_withins
  rand_full_betweens[lower:upper,] <- rand_betweens
  rand_full_totals[lower:upper,] <- rand_totals
  
  bart_full_coeffs[lower:upper,] <- bart_coeffs
  bart_full_coverage_tot[lower:upper,] <- bart_coverage_tot
  bart_full_withins[lower:upper,] <- bart_withins
  bart_full_betweens[lower:upper,] <- bart_betweens
  bart_full_totals[lower:upper,] <- bart_totals
  
  full_sim_time[lower:upper] <- sim_time
  full_mean_time[lower:upper] <- mean_time
  full_meav_time[lower:upper] <- meav_time
  full_rand_time[lower:upper] <- rand_time
  full_bart_time[lower:upper] <- bart_time
  
  full_ovt <- full_ovt + ovt
}

true_beta <- true_beta

complete_lm_coeff <- colMeans(full_complete_coeffs)
complete_lm_vcov <- colMeans(full_complete_vcovs)

names(complete_lm_coeff) <- var_names

mean_coeffs <- mean_full_coeffs
mean_bias_tru <- colMeans(mean_coeffs) - true_beta
mean_pb_tru <- 100*abs(mean_bias_tru/true_beta)
mean_coverage_tot <- colMeans(mean_full_coverage_tot)
mean_within_final <- colMeans(mean_full_withins)
mean_between_final <- colMeans(mean_full_betweens)
mean_total_final <- colMeans(mean_full_totals)

meav_coeffs <- meav_full_coeffs
meav_bias_tru <- colMeans(meav_coeffs) - true_beta
meav_pb_tru <- 100*abs(meav_bias_tru/true_beta)
meav_coverage_tot <- colMeans(meav_full_coverage_tot)
meav_within_final <- colMeans(meav_full_withins)
meav_between_final <- colMeans(meav_full_betweens)
meav_total_final <- colMeans(meav_full_totals)

rand_coeffs <- rand_full_coeffs
rand_bias_tru <- colMeans(rand_coeffs) - true_beta
rand_pb_tru <- 100*abs(rand_bias_tru/true_beta)
rand_coverage_tot <- colMeans(rand_full_coverage_tot)
rand_within_final <- colMeans(rand_full_withins)
rand_between_final <- colMeans(rand_full_betweens)
rand_total_final <- colMeans(rand_full_totals)

bart_coeffs <- bart_full_coeffs
bart_bias_tru <- colMeans(bart_coeffs) - true_beta
bart_pb_tru <- 100*abs(bart_bias_tru/true_beta)
bart_coverage_tot <- colMeans(bart_full_coverage_tot)
bart_within_final <- colMeans(bart_full_withins)
bart_between_final <- colMeans(bart_full_betweens)
bart_total_final <- colMeans(bart_full_totals)

sim_time <- full_sim_time
mean_time <- full_mean_time
meav_time <- full_meav_time
rand_time <- full_rand_time
bart_time <- full_bart_time

ovt <- full_ovt

if(sim_num == 1){
  complete_lm_vcov <- diag(complete_lm_vcov)
}

coef_names <- names(complete_lm_coeff)

#rm(results)
```

```{r,echo=FALSE}
#Comparison values:
within_target <- complete_lm_vcov

between_target_mean <- var(mean_coeffs)
between_target_meav <- var(meav_coeffs)
between_target_rand <- var(rand_coeffs)
between_target_bart <- var(bart_coeffs)

total_target_mean <- within_target + between_target_mean
total_target_meav <- within_target + between_target_meav
total_target_rand <- within_target + between_target_rand
total_target_bart <- within_target + between_target_bart
```

```{r, echo=FALSE}
params <- data.frame(SimNumber = sim_num,
                     Observations = n_obs,
                     Missingness = missp,
                     Sims = sims,
                     M = M,
                     maxiter = maxiter,
                     ntree = ntree,
                     BurnIn = num_burn_in,
                     PostBurnIn = num_iterations_after_burn_in)

knitr::kable(params)
```

```{r, echo=FALSE}
mcses <- function(sims, true_beta, coeffs, coverage){
  bias_mcse <- apply(coeffs,2, sd) / sqrt(sims)
  pb_mcse <- 100*apply(coeffs,2, sd) / (sqrt(sims) * abs(true_beta))
  coverage_mcse <- sqrt((coverage*(1-coverage))/sims)
  
  return(list(bias_mcse, pb_mcse, coverage_mcse))
}

mean_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = mean_coeffs, coverage = mean_coverage_tot)

meav_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = meav_coeffs, coverage = meav_coverage_tot)

rand_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = rand_coeffs, coverage = rand_coverage_tot)

bart_mcse <- mcses(sims = sims, true_beta = true_beta, coeffs = bart_coeffs, coverage = bart_coverage_tot)
```

```{r,echo=FALSE}
results <- tibble::tibble(Variable = c('$x_1$','','','','$x_2$','','','','${x_3}^2$','','','',"$\\sin(x_4)$",'','',''),
                    Method = c('$\\textsf{properBARTmean}$','$\\textsf{properBARTmeav}$','$\\textsf{properBARTrand}$','$\\textsf{properBARTbart}$',
                               '$\\textsf{properBARTmean}$','$\\textsf{properBARTmeav}$','$\\textsf{properBARTrand}$','$\\textsf{properBARTbart}$',
                               '$\\textsf{properBARTmean}$','$\\textsf{properBARTmeav}$','$\\textsf{properBARTrand}$','$\\textsf{properBARTbart}$',
                               '$\\textsf{properBARTmean}$','$\\textsf{properBARTmeav}$','$\\textsf{properBARTrand}$','$\\textsf{properBARTbart}$'),
                    `$\\text{PB}[\\beta_i]$` = c(paste0(round(mean_pb_tru[1], digits = roundn)," (",round(mean_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(meav_pb_tru[1], digits = roundn)," (",round(meav_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(rand_pb_tru[1], digits = roundn)," (",round(rand_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[1], digits = roundn)," (",round(bart_mcse[[2]][1], digits = roundn),")"),
                                                 paste0(round(mean_pb_tru[2], digits = roundn)," (",round(mean_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(meav_pb_tru[2], digits = roundn)," (",round(meav_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(rand_pb_tru[2], digits = roundn)," (",round(rand_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[2], digits = roundn)," (",round(bart_mcse[[2]][2], digits = roundn),")"),
                                                 paste0(round(mean_pb_tru[3], digits = roundn)," (",round(mean_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(meav_pb_tru[3], digits = roundn)," (",round(meav_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(rand_pb_tru[3], digits = roundn)," (",round(rand_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[3], digits = roundn)," (",round(bart_mcse[[2]][3], digits = roundn),")"),
                                                 paste0(round(mean_pb_tru[4], digits = roundn)," (",round(mean_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(meav_pb_tru[4], digits = roundn)," (",round(meav_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(rand_pb_tru[4], digits = roundn)," (",round(rand_mcse[[2]][4], digits = roundn),")"),
                                                 paste0(round(bart_pb_tru[4], digits = roundn)," (",round(bart_mcse[[2]][4], digits = roundn),")")),
                    `$\\mathrm{Var}_\\text{T}$` = c(round(mean_total_final[1], digits = roundn),
                                                    round(meav_total_final[1], digits = roundn),
                                                    round(rand_total_final[1], digits = roundn),
                                                    round(bart_total_final[1], digits = roundn),
                                                    round(mean_total_final[2], digits = roundn),
                                                    round(meav_total_final[2], digits = roundn),
                                                    round(rand_total_final[2], digits = roundn),
                                                    round(bart_total_final[2], digits = roundn),
                                                    round(mean_total_final[3], digits = roundn),
                                                    round(meav_total_final[3], digits = roundn),
                                                    round(rand_total_final[3], digits = roundn),
                                                    round(bart_total_final[3], digits = roundn),
                                                    round(mean_total_final[4], digits = roundn),
                                                    round(meav_total_final[4], digits = roundn),
                                                    round(rand_total_final[4], digits = roundn),
                                                    round(bart_total_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{T}^{\\left(\\text{target}\\right)}$` = c(as.character(round(total_target_mean[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_meav[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_rand[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_bart[1,1],digits = roundn)),
                                                                                    as.character(round(total_target_mean[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_meav[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_rand[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_bart[2,2],digits = roundn)),
                                                                                    as.character(round(total_target_mean[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_meav[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_rand[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_bart[3,3],digits = roundn)),
                                                                                    as.character(round(total_target_mean[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_meav[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_rand[4,4],digits = roundn)),
                                                                                    as.character(round(total_target_bart[4,4],digits = roundn))),
                    `$\\mathrm{Var}_\\text{W}$` = c(round(mean_within_final[1], digits = roundn),
                                                    round(meav_within_final[1], digits = roundn),
                                                    round(rand_within_final[1], digits = roundn),
                                                    round(bart_within_final[1], digits = roundn),
                                                    round(mean_within_final[2], digits = roundn),
                                                    round(meav_within_final[2], digits = roundn),
                                                    round(rand_within_final[2], digits = roundn),
                                                    round(bart_within_final[2], digits = roundn),
                                                    round(mean_within_final[3], digits = roundn),
                                                    round(meav_within_final[3], digits = roundn),
                                                    round(rand_within_final[3], digits = roundn),
                                                    round(bart_within_final[3], digits = roundn),
                                                    round(mean_within_final[4], digits = roundn),
                                                    round(meav_within_final[4], digits = roundn),
                                                    round(rand_within_final[4], digits = roundn),
                                                    round(bart_within_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{W}^{\\left(\\text{target}\\right)}$` = c(as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[1],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[2],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[3],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn)),
                                                                                    as.character(round(within_target[4],digits = roundn))),
                    `$\\mathrm{Var}_\\text{B}$` = c(round(mean_between_final[1], digits = roundn),
                                                    round(meav_between_final[1], digits = roundn),
                                                    round(rand_between_final[1], digits = roundn),
                                                    round(bart_between_final[1], digits = roundn),
                                                    round(mean_between_final[2], digits = roundn),
                                                    round(meav_between_final[2], digits = roundn),
                                                    round(rand_between_final[2], digits = roundn),
                                                    round(bart_between_final[2], digits = roundn),
                                                    round(mean_between_final[3], digits = roundn),
                                                    round(meav_between_final[3], digits = roundn),
                                                    round(rand_between_final[3], digits = roundn),
                                                    round(bart_between_final[3], digits = roundn),
                                                    round(mean_between_final[4], digits = roundn),
                                                    round(meav_between_final[4], digits = roundn),
                                                    round(rand_between_final[4], digits = roundn),
                                                    round(bart_between_final[4], digits = roundn)),
                    `$\\mathrm{Var}_\\text{B}^{\\left(\\text{target}\\right)}$` = c(as.character(round(between_target_mean[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_meav[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_rand[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_bart[1,1],digits = roundn)),
                                                                                    as.character(round(between_target_mean[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_meav[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_rand[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_bart[2,2],digits = roundn)),
                                                                                    as.character(round(between_target_mean[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_meav[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_rand[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_bart[3,3],digits = roundn)),
                                                                                    as.character(round(between_target_mean[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_meav[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_rand[4,4],digits = roundn)),
                                                                                    as.character(round(between_target_bart[4,4],digits = roundn))),
                    `Coverage Rate` = c(paste0(as.character(round(mean_coverage_tot[1], digits = roundn))," (",round(mean_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(meav_coverage_tot[1], digits = roundn))," (",round(meav_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(rand_coverage_tot[1], digits = roundn))," (",round(rand_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[1], digits = roundn))," (",round(bart_mcse[[3]][1], digits = roundn),")"),
                                        paste0(as.character(round(mean_coverage_tot[2], digits = roundn))," (",round(mean_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(meav_coverage_tot[2], digits = roundn))," (",round(meav_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(rand_coverage_tot[2], digits = roundn))," (",round(rand_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[2], digits = roundn))," (",round(bart_mcse[[3]][2], digits = roundn),")"),
                                        paste0(as.character(round(mean_coverage_tot[3], digits = roundn))," (",round(mean_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(meav_coverage_tot[3], digits = roundn))," (",round(meav_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(rand_coverage_tot[3], digits = roundn))," (",round(rand_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[3], digits = roundn))," (",round(bart_mcse[[3]][3], digits = roundn),")"),
                                        paste0(as.character(round(mean_coverage_tot[4], digits = roundn))," (",round(mean_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(meav_coverage_tot[4], digits = roundn))," (",round(meav_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(rand_coverage_tot[4], digits = roundn))," (",round(rand_mcse[[3]][4], digits = roundn),")"),
                                        paste0(as.character(round(bart_coverage_tot[4], digits = roundn))," (",round(bart_mcse[[3]][4], digits = roundn),")")))

knitr::kable(results, escape = FALSE)
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(sim_time[sim_out:length(sim_time)]),
                       Time = sim_time[sim_out:length(sim_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "lightgreen") +
  labs(title = "Plot showing the time take for each simulation.",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(mean_time[sim_out:length(mean_time)]),
                       Time = mean_time[sim_out:length(mean_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#000080") +
  labs(title = "Plot showing the time take for each properBARTmean process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(meav_time[sim_out:length(meav_time)]),
                       Time = meav_time[sim_out:length(meav_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#f7a502") +
  labs(title = "Plot showing the time take for each properBARTmeav process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(rand_time[sim_out:length(rand_time)]),
                       Time = rand_time[sim_out:length(rand_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#e93e6f") +
  labs(title = "Plot showing the time take for each properBARTrand process",
       y = "Time (seconds)")
```

```{r, echo=FALSE}

sim_out <- 1

sims <- data.frame(Simulation = seq_along(bart_time[sim_out:length(bart_time)]),
                       Time = bart_time[sim_out:length(bart_time)])

ggplot(data=sims, aes(x = Simulation,y = Time)) +
  geom_line(colour = "#089cc0") +
  labs(title = "Plot showing the time take for each properBARTbart process",
       y = "Time (seconds)")
```

\hspace{10cm}

```{r, echo=FALSE}
ovt_mins <- ovt/60
ovt_hours <- ovt_mins/60
if(ovt_hours>2){
  rep_ovt <- ovt_hours
  com_ovt <- 'hours.'
} else if(ovt_mins>2){
  rep_ovt <- ovt_mins
  com_ovt <- 'minutes.'
} else{
  rep_ovt <- ovt
  com_ovt <- 'seconds.'
}
```

### Overall Time: `r rep_ovt` `r com_ovt`

```{r, echo=FALSE}
vals <- true_beta

colnames(mean_coeffs) <- coef_names
colnames(meav_coeffs) <- coef_names
colnames(rand_coeffs) <- coef_names
colnames(bart_coeffs) <- coef_names

coefs.tb <- bind_rows(
  as_tibble(mean_coeffs) %>%
    mutate(Method = "${properBARTmean}$", Sim = row_number()),
  as_tibble(meav_coeffs) %>%
    mutate(Method = "${properBARTmeav}$", Sim = row_number()),
  as_tibble(rand_coeffs) %>%
    mutate(Method = "${properBARTrand}$", Sim = row_number()),
  as_tibble(bart_coeffs) %>%
    mutate(Method = "${properBARTbart}$", Sim = row_number())
) %>%
  pivot_longer(
    cols = all_of(coef_names),
    names_to = "Estimates",
    values_to = "coefs"
  ) %>%
  mutate(
    Method = factor(
      Method,
      levels = c(
        "${properBARTmean}$",
        "${properBARTmeav}$",
        "${properBARTrand}$",
        "${properBARTbart}$"
      )
    ),
    Estimates = factor(Estimates, levels = coef_names)
  )

true.line <- tibble(
  Estimates = factor(coef_names, levels = coef_names),
  mean.hat = vals
)

colours <- c(
  "${properBARTmean}$" = "#000080",
  "${properBARTmeav}$" = "#f7a502",
  "${properBARTrand}$" = "#e93e6f",
  "${properBARTbart}$" = "#089cc0"
)

labels.names <- c(
  "${properBARTmean}$" = TeX("${properBARTmean}$"),
  "${properBARTmeav}$" = TeX("${properBARTmeav}$"),
  "${properBARTrand}$" = TeX("${properBARTrand}$"),
  "${properBARTbart}$" = TeX("${properBARTbart}$")
)

ggplot(
  coefs.tb,
  aes(x = coefs, y = Method, color = Method, fill = Method)
) +
  geom_boxplot(width = 0.2, outlier.color = NA, alpha = 0.5) +
  facet_wrap(
    vars(Estimates),
    scales = "free_x",
    nrow = 2,
    labeller = label_parsed
  ) +
  geom_vline(
    data = true.line,
    aes(xintercept = mean.hat),
    linetype = "dashed"
  ) +
  scale_color_manual(values = colours) +
  scale_fill_manual(values = colours) +
  scale_y_discrete(labels = labels.names) +
  guides(color = "none", fill = "none") +
  labs(x = "Coefficient", y = "Method") +
  theme(
    axis.title.x = element_text(size = 26, margin = margin(t = 10)),
    axis.title.y = element_text(size = 26, margin = margin(r = 10)),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 18),
    strip.text.x = element_text(size = 18),
    panel.spacing.x = unit(0.35, "in"),
    panel.spacing.y = unit(0.2, "in")
  )
```


```{r, echo=FALSE}
true_between <- list(
  `properBARTmean` = diag(var(mean_coeffs)),
  `properBARTmeav` = diag(var(meav_coeffs)),
  `properBARTrand`   = diag(var(rand_coeffs)),
  `properBARTbart` = diag(var(bart_coeffs))
)

plot_df <- bind_rows(
  tibble(
    Estimates = coef_names,
    Method = "properBARTmean",
    Between = as.numeric(mean_between_final),
    True.Between = true_between$`properBARTmean`
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTmeav",
    Between = as.numeric(meav_between_final),
    True.Between = true_between$`properBARTmeav`
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTrand",
    Between = as.numeric(rand_between_final),
    True.Between = true_between$`properBARTrand`
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTbart",
    Between = as.numeric(bart_between_final),
    True.Between = true_between$`properBARTbart`
  )
) %>%
  mutate(
    reratio.between = Between / True.Between - 1
  ) %>%
  pivot_longer(
    cols = c(reratio.between),
    names_to = "Type",
    values_to = "Value"
  ) %>%
  mutate(
    Estimates = factor(Estimates, levels = coef_names),
    Method = factor(Method, levels = c("properBARTmean","properBARTmeav","properBARTrand","properBARTbart")),
    Type = factor(
      Type,
      levels = c("reratio.between"),
      labels = c(
        "Var[B] / Var[B]^{target} - 1"
      )
    )
  )

colours <- c(
  "properBARTmean" = "#000080",
  "properBARTmeav" = "#f7a502",
  "properBARTrand" = "#e93e6f",
  "properBARTbart" = "#089cc0"
)

ggplot(
  plot_df,
  aes(x = Method, y = Value, fill = Method)
) +
  geom_col(position = "dodge") +
  facet_grid(
    Type ~ Estimates,
    switch = "y",
    labeller = label_parsed
  ) +
  scale_fill_manual(values = colours) +
  labs(
    x = "Method",
    y = "Relative Ratio"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text.y = element_text(size = 14, face = "bold"),
    strip.text.x = element_text(size = 12, face = "bold"),
    panel.spacing = unit(0.2, "in"),
    legend.position = "none"
  )
```

```{r, echo=FALSE}
true_within <- complete_lm_vcov

plot_df <- bind_rows(
  tibble(
    Estimates = coef_names,
    Method = "properBARTmean",
    Within = as.numeric(mean_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTmeav",
    Within = as.numeric(meav_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTrand",
    Within = as.numeric(rand_within_final),
    True.Within = true_within,
  ),
  tibble(
    Estimates = coef_names,
    Method = "properBARTbart",
    Within = as.numeric(bart_within_final),
    True.Within = true_within,
  )
) %>%
  mutate(
    reratio.within  = Within  / True.Within  - 1
  ) %>%
  pivot_longer(
    cols = c(reratio.within),
    names_to = "Type",
    values_to = "Value"
  ) %>%
  mutate(
    Estimates = factor(Estimates, levels = coef_names),
    Method = factor(Method, levels = c("properBARTmean","properBARTmeav","properBARTrand","properBARTbart")),
    Type = factor(
      Type,
      levels = c("reratio.within"),
      labels = c(
        "Var[W] / Var[W]^{target} - 1"
      )
    )
  )

colours <- c(
  "properBARTmean" = "#000080",
  "properBARTmeav" = "#f7a502",
  "properBARTrand" = "#e93e6f",
  "properBARTbart" = "#089cc0"
)

ggplot(
  plot_df,
  aes(x = Method, y = Value, fill = Method)
) +
  geom_col(position = "dodge") +
  facet_grid(
    Type ~ Estimates,
    switch = "y",
    labeller = label_parsed
  ) +
  scale_fill_manual(values = colours) +
  labs(
    x = "Method",
    y = "Relative Ratio"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text.y = element_text(size = 14, face = "bold"),
    strip.text.x = element_text(size = 12, face = "bold"),
    panel.spacing = unit(0.2, "in"),
    legend.position = "none"
  )
```

